import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// These guard that the generated mockups actually cover every screen and state
// the issue asks about — so the pictures can't quietly stop showing the cases
// they exist to answer.
//
// They are now assertions about *coverage*, not fidelity. The mockups are
// rendered from the production components by `npm run build:mockups`, so "does
// the mockup match production?" is answered by construction; what a test can
// still get wrong is generating a page that happens to contain none of the
// interesting states. Regenerate before running these if components changed.

const read = (name: string) =>
  readFileSync(fileURLToPath(new URL(name, import.meta.url)), "utf8");

const LIST_VIEWS = ["./popup.html", "./jobs.html"];

/** One `<button>` out of a page, picked by an attribute it carries. Radix writes
 *  `data-state` ahead of the caller's own props, so the two cannot be matched
 *  left-to-right in a single regex. */
function buttonWith(markup: string, attr: string): string {
  const found = markup.split("<button").find((chunk) => chunk.includes(attr));
  assert.ok(found, `no <button> carrying ${attr}`);
  return found;
}

/** Just that button's opening tag — its own attributes and nothing else.
 *  {@link buttonWith} runs to the *next* `<button`, which for the last control on
 *  a row is most of the row after it, so asking "does this button have class X?"
 *  of the whole chunk answers about the next row too. Slicing at the first `>` is
 *  safe: React escapes the `>` inside class names like `has-[>svg]:px-2.5`. */
function tagOf(markup: string, attr: string): string {
  const chunk = buttonWith(markup, attr);
  return chunk.slice(0, chunk.indexOf(">"));
}

test("every mockup is generated from the components, not hand-authored", () => {
  for (const name of [...LIST_VIEWS, "./states.html", "./options.html"]) {
    assert.match(read(name), /GENERATED by `npm run build:mockups`/, name);
  }
});

test("popup shows the list at its real popup width, defaulting to New", () => {
  const html = read("./popup.html");
  assert.match(html, /data-variant="popup"/);
  // 380px, in Tailwind's own spacing scale.
  assert.match(html, /\bw-95\b/);
  assert.match(buttonWith(html, 'data-mode="new"'), /data-state="on"/);
});

test("jobs tab reuses the same component in the wider tab view, defaulting to All", () => {
  const html = read("./jobs.html");
  assert.match(html, /data-variant="tab"/);
  // Full-bleed header and footer, with the list column capped at 880px — a job
  // title stretched across a 27" monitor is unreadable, not spacious.
  assert.match(html, /\bh-screen\b/);
  assert.match(html, /\bmax-w-220\b/);
  assert.match(buttonWith(html, 'data-mode="all"'), /data-state="on"/);
});

test("the tab shows the two ages, the mode chip and a logged note", () => {
  // The row facts the redesign added, each present in at least one mockup row so
  // the picture can't quietly stop showing them.
  const html = read("./jobs.html");
  assert.match(html, /Posted \d+[a-z]+ ago/);
  assert.match(html, /Found \d+[a-z]+ ago/);
  assert.match(html, />Remote</);
  assert.match(html, /data-applied="true"/);
  assert.match(html, /Cover letter v3/);
});

test("both popup and tab carry the watch chips and the New/All toggle", () => {
  for (const name of LIST_VIEWS) {
    const html = read(name);
    assert.match(html, /data-watch-id=""[^>]*>All watches/, `${name} chips`);
    assert.match(html, /data-mode="new"/, `${name} New`);
    assert.match(html, /data-mode="all"/, `${name} All`);
  }
});

test("both popup and tab carry the manual scan control", () => {
  // In both header rows — with words in the tab, icon-only in the 380px popup.
  for (const name of LIST_VIEWS) {
    assert.match(read(name), /id="scan-now"[^>]*data-scan-state="(idle|scanning)"/, name);
  }
});

test("the popup folds its header controls into a hamburger, and shows the menu", () => {
  const popup = read("./popup.html");
  // The hamburger in the header…
  assert.match(popup, /id="header-menu"/);
  assert.match(popup, /lucide-menu/);
  // …and the three it stands for, in the frame beside it, each with its words.
  assert.match(popup, /data-slot="header-menu"/);
  for (const label of ["Mark all as read", "Options"]) {
    assert.match(popup, new RegExp(`>${label}<`), label);
  }
  // "Scan now" is not one of them: it is the control you press most, so it stays
  // out in the header beside the hamburger, icon-only, its label the aria-label.
  assert.match(popup, /id="scan-now"[^>]*aria-label="Scan now"/);
  assert.doesNotMatch(popup, />Scan now</);
  // The tab keeps them in a row and needs no menu button.
  assert.doesNotMatch(read("./jobs.html"), /id="header-menu"/);
});

test("the popup offers to open the list as a full page; the tab already is one", () => {
  // Beside the hamburger rather than inside it: the escape from a 380px panel
  // should not be behind the menu you are escaping.
  assert.match(read("./popup.html"), /id="open-tab"[^>]*aria-label="Open as a full page"/);
  // The tab does not render it at all. This used to be a CSS rule hiding a
  // button both views emitted, because they shared one markup string; the
  // component branches on its variant instead, so there is nothing to hide.
  assert.doesNotMatch(read("./jobs.html"), /id="open-tab"/);
});

test("both views carry the scan status bar, showing its two everyday states", () => {
  // The bar is the only thing on the page that says the loop is alive, so both
  // sides of it are worth seeing: counting down in the popup, mid-scan in the tab.
  assert.match(read("./popup.html"), /data-kind="waiting"[\s\S]*Next scan in \d+m \d+s/);
  assert.match(read("./jobs.html"), /data-kind="scanning"[\s\S]*Scanning for new jobs…/);
});

test("the tab shows read jobs staying on screen in All mode", () => {
  const html = read("./jobs.html");
  assert.match(html, /data-read="true"/);
  assert.match(html, /data-read="false"/);
});

test("both views show an opened job staying on screen, highlighted rather than gone", () => {
  for (const name of LIST_VIEWS) {
    // data-opened + data-read="false" on the same row is the whole point: you
    // clicked through to it and it is still in the list.
    assert.match(read(name), /data-read="false" data-opened="true"/, name);
  }
});

test("every row carries its own read and block buttons", () => {
  for (const name of LIST_VIEWS) {
    const html = read(name);
    assert.match(html, /data-action="read"/, `${name} read`);
    assert.match(html, /data-action="block"/, `${name} block`);

    // The buttons sit outside the anchor — a <button> inside <a> is invalid
    // HTML. Check each anchor's own body, not the file as a whole, or the match
    // runs past </a> into the next row's buttons.
    for (const [, body] of html.matchAll(/<a [^>]*href="https:\/\/www\.linkedin[^>]*>([\s\S]*?)<\/a>/g)) {
      assert.doesNotMatch(body!, /<button/, `${name} button inside anchor`);
    }
  }
});

test("both views show a blocked company greyed and tagged, still on screen", () => {
  for (const name of LIST_VIEWS) {
    const html = read(name);
    assert.match(html, /data-blocked="true"/, `${name} state`);
    assert.match(html, />Blocked</, `${name} tag`);
    // Blocking is undoable from the row it was pressed on, and the button says
    // so in words rather than leaving it to a tooltip.
    assert.match(html, /data-action="block"[^>]*aria-pressed="true"/, `${name} unblock`);
    assert.match(html, />Unblock</, `${name} unblock label`);
  }
});

test("both views spell the block action out, before the row's tick", () => {
  for (const name of LIST_VIEWS) {
    const html = read(name);
    assert.match(html, />Block</, `${name} label`);
    // Block first, tick out at the edge — the order JobRow renders them in.
    const row = /data-job-id="1"[\s\S]*?data-job-id="2"/.exec(html)?.[0];
    assert.ok(row, `${name} has a first row to inspect`);
    assert.ok(
      row!.indexOf('data-action="block"') < row!.indexOf('data-action="read"'),
      `${name} block button before read button`,
    );
  }
});

test("the two views place the same buttons two different ways", () => {
  // The popup's actions own the line under the posting and split it evenly;
  // the tab's sit beside the posting at their natural size, tick unlabelled.
  const popup = read("./popup.html");
  assert.match(tagOf(popup, 'data-action="block"'), /\bflex-1\b/);
  assert.match(tagOf(popup, 'data-action="read"'), /\bflex-1\b/);
  assert.match(popup, />Mark as read</);

  const tab = read("./jobs.html");
  assert.doesNotMatch(tagOf(tab, 'data-action="block"'), /\bflex-1\b/);
  assert.doesNotMatch(tagOf(tab, 'data-action="read"'), /\bflex-1\b/);
  // Only as the tooltip and the accessible name, never as a fifth line of text.
  assert.doesNotMatch(tab, />Mark as read</);
  assert.match(tab, /data-action="read"[^>]*aria-label="Mark as read"/);
});

test("the tab shows a Block button mid-question, waiting for the second press", () => {
  // Blocking hides every future job from a company, so it asks first; the mockup
  // carries that state because it is the one you can't discover from a resting row.
  const html = read("./jobs.html");
  assert.match(html, /data-armed="true"/);
  assert.match(html, /aria-label="Block [^"]* — press again to confirm"/);
  assert.match(html, /Sure\?/);
});

test("the tab shows the read toggle flipped to its undo state", () => {
  assert.match(read("./jobs.html"), /data-action="read"[^>]*aria-pressed="true"/);
});

test("a job row degrades when a field is missing (no dangling separator)", () => {
  // The popup includes a row whose meta is company-only (location missing).
  assert.match(read("./popup.html"), />Momo Financial</);
});

test("all five empty/degraded states are present in the showcase", () => {
  const html = read("./states.html");
  for (const kind of ["no-watches", "no-jobs-yet", "no-new", "scanning", "scan-error"]) {
    assert.match(html, new RegExp(`data-kind="${kind}"`), kind);
  }
});

test("the options mockup carries the two banners a healthy page never shows", () => {
  const html = read("./options.html");
  assert.match(html, /data-severity="warn"[\s\S]*Send test message/);
  assert.match(html, /data-severity="error"/);
});

test("the options mockup carries the how-it-works explainer and its repo link", () => {
  // The one part of that page with no storage behind it, so it is the one part
  // the mockup can show for real rather than describe.
  const html = read("./options.html");
  assert.match(html, /id="how-it-works"/);
  assert.match(html, /href="https:\/\/github\.com\/jochristianto\/jc-linkedin-job-watcher"/);
});

test("every mockup draws its icons as Lucide SVG, never a font glyph", () => {
  const glyphs = /[\u{2190}-\u{21FF}\u{2200}-\u{22FF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{1F300}-\u{1FAFF}]/u;
  for (const name of [...LIST_VIEWS, "./states.html", "./options.html"]) {
    const html = read(name);
    assert.match(html, /class="lucide lucide-/, `${name} has Lucide icons`);
    assert.doesNotMatch(html, glyphs, `${name} has no leftover glyph or emoji`);
  }
});

test("the mockups' icons are the ones the components ask for, icon for icon", () => {
  const rows = read("./popup.html") + read("./jobs.html");
  assert.match(rows, /data-action="read"[^>]*>\s*<svg[^>]*lucide-eye-off/);
  assert.match(rows, /data-action="block"[^>]*>\s*<svg[^>]*lucide-ban/);
  assert.match(rows, /lucide-settings/);

  const states = read("./states.html");
  for (const name of ["search", "sprout", "circle-check", "refresh-cw", "triangle-alert"]) {
    assert.match(states, new RegExp(`lucide-${name}`), name);
  }
});

test("styling ships both light and dark via prefers-color-scheme, no theme toggle", () => {
  // The stylesheet is inlined into each mockup, so this reads the real compiled
  // Tailwind output rather than a separate hand-kept token file.
  const html = read("./popup.html");
  assert.match(html, /:root\s*{/);
  assert.match(html, /prefers-color-scheme:\s*dark/);
});
