// Regenerate mockups/*.html from the real components — `npm run build:mockups`.
//
// The mockups used to be hand-authored HTML that mirrored what render.ts
// emitted, with a note admitting it was "not the compiled component". That was
// affordable when the component *was* a string template; against React + Tailwind
// it would be a guaranteed lie, since the classes come out of the components and
// the CSS out of the compiler.
//
// So they are generated now: the same components production mounts, rendered to
// static HTML with fake data, over the real compiled stylesheet inlined into a
// <style> block. The important property survives — a committed file you can open
// straight from `file://` with no build step and no extension — and the drift
// cannot.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";

import { EmptyState } from "../src/components/empty-state.tsx";
import { HealthBanner } from "../src/components/health-banner.tsx";
import { JobList } from "../src/components/job-list.tsx";
import { ListHeader } from "../src/components/list-header.tsx";
import { ScanStatusBar } from "../src/components/scan-status.tsx";
import { Toolbar } from "../src/components/toolbar.tsx";
import { TooltipProvider } from "../src/components/ui/tooltip";
import type { EmptyKind, JobView, ListMode, ScanStatus, ViewVariant } from "../src/view-model.ts";

const root = resolve(import.meta.dirname, "..");
const noop = () => {};

// ── The compiled stylesheet ─────────────────────────────────────────────────
// Tailwind v4 finds its own sources by scanning out from the input CSS file, so
// this picks up every class in src/components/ with no config to keep in step.

function compileCss(): string {
  const dir = mkdtempSync(join(tmpdir(), "ljw-mockups-"));
  try {
    const out = join(dir, "mockups.css");
    execFileSync(
      "npx",
      ["@tailwindcss/cli", "-i", join(root, "src/tokens.css"), "-o", out, "--minify"],
      { cwd: root, stdio: ["ignore", "ignore", "inherit"] },
    );
    return readFileSync(out, "utf8");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// ── Fake data ───────────────────────────────────────────────────────────────

function job(over: Partial<JobView> = {}): JobView {
  return {
    id: "3901",
    title: "Senior Software Engineer",
    company: "Acme Corp",
    location: "Jakarta, Indonesia",
    postedText: "2 hours ago",
    watchName: "Indonesia",
    url: "https://www.linkedin.com/jobs/view/3901/",
    opened: false,
    read: false,
    blocked: false,
    ...over,
  };
}

const WATCHES = [
  { id: "w1", name: "Indonesia" },
  { id: "w2", name: "Japan" },
];

/** The popup's list: unread rows, one already opened, one whose location never
 *  parsed (the field-missing case), one blocked company still on screen. */
const POPUP_JOBS: JobView[] = [
  job({ id: "1", title: "Senior Backend Engineer (Go)", company: "Tokopedia", postedText: "12 minutes ago" }),
  job({ id: "2", title: "Staff Engineer, Platform", company: "GoTo Financial", location: "Jakarta", postedText: "1 hour ago", opened: true }),
  // Location never parsed — the meta line must not leave a dangling separator.
  job({ id: "3", title: "Principal Engineer", company: "Momo Financial", location: "", postedText: "3 hours ago" }),
  job({ id: "4", title: "Engineering Manager", company: "Blocked Recruiters Ltd", location: "Remote", postedText: "5 hours ago", blocked: true }),
];

/** The tab's list: everything the popup shows plus the states only "All" mode
 *  reaches — a read row still on screen, and a Block button mid-question. */
const TAB_JOBS: JobView[] = [
  ...POPUP_JOBS,
  job({ id: "5", title: "Distinguished Engineer", company: "Grab", location: "Singapore", postedText: "yesterday", watchName: "Japan", read: true }),
  job({ id: "6", title: "Head of Engineering", company: "Sea Group", location: "Singapore", postedText: "yesterday", watchName: "Japan" }),
];

// ── Page shells ─────────────────────────────────────────────────────────────

function page(title: string, css: string, body: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${title}</title>
    <!-- GENERATED by \`npm run build:mockups\` — do not edit by hand.
         Rendered from the real components in src/components/, over the real
         compiled Tailwind stylesheet. Light and dark both ship; dark follows the
         OS through prefers-color-scheme, with no JS. -->
    <style>
${css}
    </style>
  </head>
  <body>
${body}
  </body>
</html>
`;
}

/** The list view, assembled exactly as `<ListView>` assembles it — minus the
 *  storage reads, with the state passed in instead. */
function listView(opts: {
  variant: ViewVariant;
  title: string;
  badge: number;
  jobs: JobView[];
  mode: ListMode;
  activeWatchId: string | null;
  status: ScanStatus;
  armedBlockId?: string | null;
  banner?: { message: string; severity: "warn" | "error" };
}): string {
  return renderToStaticMarkup(
    <TooltipProvider>
      <div
        data-variant={opts.variant}
        className={
          opts.variant === "popup"
            ? "flex h-[600px] min-h-[480px] w-[380px] flex-col bg-background"
            : "mx-auto flex min-h-screen max-w-[720px] flex-col border-x bg-background"
        }
      >
        <ListHeader
          title={opts.title}
          badge={opts.badge}
          scanButton={opts.status.kind === "scanning" ? "scanning" : "idle"}
          variant={opts.variant}
          enabled={opts.status.kind !== "disabled"}
          onToggleEnabled={noop}
          onScan={noop}
          onMarkAllRead={noop}
          onOpenTab={noop}
          onOpenOptions={noop}
        />
        <Toolbar
          watches={WATCHES}
          activeWatchId={opts.activeWatchId}
          mode={opts.mode}
          onWatchChange={noop}
          onModeChange={noop}
        />
        {opts.banner && (
          <HealthBanner message={opts.banner.message} severity={opts.banner.severity} />
        )}
        <div className="flex flex-1 flex-col overflow-y-auto px-2 pb-2">
          <JobList
            jobs={opts.jobs}
            mode={opts.mode}
            armedBlockId={opts.armedBlockId ?? null}
            onOpen={noop}
            onToggleRead={noop}
            onBlock={noop}
          />
        </div>
        <ScanStatusBar status={opts.status} />
      </div>
    </TooltipProvider>,
  );
}

const EMPTY_KINDS: EmptyKind[] = ["no-watches", "no-jobs-yet", "no-new", "scanning", "scan-error"];

/** All five empty/degraded states side by side, each in a popup-width frame so
 *  they are seen at the size they actually appear. */
function statesShowcase(): string {
  return renderToStaticMarkup(
    <TooltipProvider>
      <div className="mx-auto flex max-w-[1200px] flex-col gap-6 p-8">
        <h1 className="text-lg font-semibold">Empty &amp; degraded states</h1>
        <div className="flex flex-wrap gap-5">
          {EMPTY_KINDS.map((kind) => (
            <figure key={kind} className="flex flex-col gap-2">
              <figcaption className="font-mono text-xs text-muted-foreground">{kind}</figcaption>
              <div className="flex h-[280px] w-[360px] flex-col rounded-lg border bg-background">
                <EmptyState kind={kind} />
              </div>
            </figure>
          ))}
        </div>
      </div>
    </TooltipProvider>,
  );
}

// ── Write them ──────────────────────────────────────────────────────────────

const css = compileCss();

const files: Record<string, string> = {
  "popup.html": page(
    "Popup — LinkedIn Job Watcher",
    css,
    listView({
      variant: "popup",
      title: "New jobs",
      badge: 3,
      jobs: POPUP_JOBS,
      mode: "new",
      activeWatchId: null,
      status: { kind: "waiting", remainingMs: 252_000, quiet: false },
    }),
  ),
  "jobs.html": page(
    "Jobs tab — LinkedIn Job Watcher",
    css,
    listView({
      variant: "tab",
      title: "LinkedIn Job Watcher",
      badge: 4,
      jobs: TAB_JOBS,
      mode: "all",
      activeWatchId: null,
      // The state you cannot discover by looking at a resting row.
      armedBlockId: "6",
      status: { kind: "scanning" },
    }),
  ),
  "states.html": page("States — LinkedIn Job Watcher", css, statesShowcase()),
  "options.html": page(
    "Options — LinkedIn Job Watcher",
    css,
    // The Options page reads chrome.storage on mount, so it cannot be rendered
    // headlessly the way the list view can. It gets the banner pair instead —
    // the two things on that page a screenshot would otherwise never show.
    renderToStaticMarkup(
      <div className="mx-auto flex max-w-3xl flex-col gap-4 p-8">
        <h1 className="text-xl font-semibold">LinkedIn Job Watcher — Settings</h1>
        <p className="text-sm text-muted-foreground">
          The settings page is a live form over <code>chrome.storage</code>, so it is not
          rendered here — load the unpacked extension and open Options to see it. Its two
          transient banners are below, since neither shows on a healthy first open.
        </p>
        <HealthBanner
          message="Telegram push has been failing — run Send test message"
          severity="warn"
          className="rounded-md border"
        />
        <HealthBanner
          message="Signed out of LinkedIn — scanning paused."
          severity="error"
          className="rounded-md border"
        />
      </div>,
    ),
  ),
};

for (const [name, html] of Object.entries(files)) {
  const path = join(root, "mockups", name);
  writeFileSync(path, html);
  console.log(`  wrote mockups/${name}  (${(html.length / 1024).toFixed(0)} kB)`);
}
